name: SDO_EUI_workshop
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
    - ipykernel
    - sunpy[all]
    - reproject
    - sunpy-soar
    - ipywidgets
    - astroquery
    - jupyterlab
